# Generated by Django 6.0.5 on 2026-05-19 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('paradas', models.ManyToManyField(to='rutas.parada')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('ultima_latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ultima_longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('ruta_asignada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flota.ruta')),
            ],
        ),
    ]
