# Generated by Django 6.0.5 on 2026-05-19 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
        ('rutas', '0002_remove_parada_latitud_remove_parada_longitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='ruta_asignada',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='ultima_latitud',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='ultima_longitud',
        ),
        migrations.AddField(
            model_name='unidad',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='modelo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidad',
            name='ruta_actual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rutas.ruta'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='placa',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.DeleteModel(
            name='Ruta',
        ),
    ]
