# Generated by Django 6.0.5 on 2026-05-19 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0002_remove_unidad_ruta_asignada_and_more'),
        ('rutas', '0004_parada_tiempo_caminando'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='chofer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='unidad', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidad',
            name='en_servicio',
            field=models.BooleanField(default=False, verbose_name='¿Transmitiendo en vivo?'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='modelo',
            field=models.CharField(help_text='Ej: Encava Ent-610', max_length=50),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='placa',
            field=models.CharField(max_length=15, unique=True, verbose_name='Placa del Autobús'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='ruta_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rutas.ruta'),
        ),
    ]
