# Generated by Django 6.0.5 on 2026-05-24 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0003_unidad_chofer_unidad_en_servicio_alter_unidad_modelo_and_more'),
        ('rutas', '0012_parada_tiempo_caminando_campana'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='chofer',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='en_servicio',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='placa',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='ruta_actual',
        ),
        migrations.AddField(
            model_name='unidad',
            name='conductor',
            field=models.OneToOneField(blank=True, limit_choices_to={'is_staff': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unidad',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'En Ruta'), ('MANTENIMIENTO', 'En Taller'), ('INACTIVO', 'Fuera de Servicio')], default='INACTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='unidad',
            name='latitud_actual',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='unidad',
            name='longitud_actual',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='unidad',
            name='numero_unidad',
            field=models.CharField(default=1, help_text='Ej: Control 05', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidad',
            name='ruta_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades', to='rutas.ruta'),
        ),
    ]
