# Generated by Django 6.0.5 on 2026-05-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0006_auto_20260524_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='modelo',
            field=models.CharField(default='Genérico', help_text='Ej: Encava Ent-610', max_length=50),
        ),
        migrations.AddField(
            model_name='unidad',
            name='placa',
            field=models.CharField(default='S/N', max_length=15, unique=True, verbose_name='Placa del Autobús'),
        ),
    ]
