# Generated by Django 6.0.5 on 2026-05-26 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0007_unidad_modelo_unidad_placa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='placa',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='ruta_asignada',
        ),
        migrations.AddField(
            model_name='unidad',
            name='propietario_flota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flota_propia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_asignado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='estado',
            field=models.CharField(choices=[('operativa', 'Operativa (En Ruta)'), ('inactiva', 'Inactiva (Fuera de Servicio)'), ('averiada', 'Averiada / En Taller')], default='inactiva', max_length=20),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='latitud_actual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='longitud_actual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='numero_unidad',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
