# Generated by Django 6.0.5 on 2026-05-26 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0008_remove_unidad_modelo_remove_unidad_placa_and_more'),
        ('rutas', '0013_alter_ruta_paradas'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='ruta_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses_en_ruta', to='rutas.ruta'),
        ),
    ]
