# Generated by Django 6.0.5 on 2026-05-19 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_asistencia', models.CharField(choices=[('NINGUNA', 'Ninguna'), ('VISUAL', 'Discapacidad Visual'), ('MOTORA', 'Discapacidad Motora'), ('MAYOR', 'Adulto Mayor'), ('MENOR', 'Menor de Edad / Escolar'), ('COGNITIVA', 'Discapacidad Cognitiva / Autismo')], default='NINGUNA', max_length=20)),
                ('telefono_emergencia', models.CharField(help_text='Número con código de país, ej: +584141234567', max_length=20)),
                ('nombre_contacto', models.CharField(help_text='Nombre de a quién avisar (Ej: Mamá, Cuidador)', max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
