# Generated by Django 6.0.5 on 2026-05-20 15:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('relacion', models.CharField(choices=[('HIJO', 'Hijo/a'), ('PADRE', 'Padre/Madre (Adulto Mayor)'), ('OTRO', 'Familiar / Otro')], max_length=20)),
                ('condicion_medica', models.TextField(blank=True, help_text='Alergias, tipo de sangre, medicamentos...', null=True)),
                ('telefono_emergencia', models.CharField(help_text='A dónde llamar si escanean el NFC', max_length=20)),
                ('token_nfc', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependientes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
