# Generated by Django 6.0.5 on 2026-05-20 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_dependiente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
