# Generated by Django 6.0.5 on 2026-05-26 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_tarjetanfc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('rol', models.CharField(choices=[('ciudadano', 'Ciudadano Normal'), ('conductor', 'Dueño de Unidad / Conductor'), ('flota', 'Dueño de Flota')], default='ciudadano', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_unidad', models.CharField(max_length=10, unique=True)),
                ('latitud_actual', models.FloatField(blank=True, null=True)),
                ('longitud_actual', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('operativa', 'Operativa (En Ruta)'), ('inactiva', 'Inactiva (Fuera de Servicio)'), ('averiada', 'Averiada / En Taller')], default='inactiva', max_length=20)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(blank=True, limit_choices_to={'perfil__rol': 'conductor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('propietario_flota', models.ForeignKey(blank=True, limit_choices_to={'perfil__rol': 'flota'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flota', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
