# Generated by Django 6.0.5 on 2026-05-26 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_perfilusuario_unidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='ultima_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SolicitudOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('experiencia_anios', models.IntegerField(help_text='Años de experiencia manejando unidades pesadas')),
                ('tipo_licencia', models.CharField(help_text='Ej: Título de 5ta', max_length=50)),
                ('mensaje', models.TextField(blank=True, help_text='¿Por qué desea unirse a nuestra red?')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Unidad',
        ),
    ]
