# Generated by Django 6.0.5 on 2026-05-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_perfilusuario_ultima_modificacion_solicitudoperador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_cambio_nombre',
            field=models.DateTimeField(blank=True, help_text='Fecha del último cambio de nombre', null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nombre_flota',
            field=models.CharField(blank=True, help_text='Nombre público de la empresa/flota', max_length=100, null=True),
        ),
    ]
