# Generated by Django 6.0.5 on 2026-06-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_perfilusuario_fecha_cambio_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='correo_emergencia',
            field=models.EmailField(blank=True, help_text='Correo del familiar que recibirá la alerta SOS', max_length=255, null=True),
        ),
    ]
