# Generated by Django 6.0.5 on 2026-06-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_perfilusuario_correo_emergencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetanfc',
            name='codigo_uid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
