# Generated by Django 6.0.5 on 2026-05-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parada',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='parada',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='parada',
            name='patrocinador',
        ),
        migrations.RemoveField(
            model_name='parada',
            name='tiene_relieve',
        ),
        migrations.RemoveField(
            model_name='patrocinador',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='patrocinador',
            name='mensaje_promocional',
        ),
        migrations.AlterField(
            model_name='parada',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('paradas', models.ManyToManyField(to='rutas.parada')),
            ],
        ),
    ]
