# Generated by Django 6.0.5 on 2026-05-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_remove_parada_latitud_remove_parada_longitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parada',
            name='latitud',
            field=models.FloatField(default=8.2968),
        ),
        migrations.AddField(
            model_name='parada',
            name='longitud',
            field=models.FloatField(default=-62.7112),
        ),
    ]
