# Generated by Django 6.0.5 on 2026-05-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0003_parada_latitud_parada_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='parada',
            name='tiempo_caminando',
            field=models.IntegerField(default=5),
        ),
    ]
