# Generated by Django 6.0.5 on 2026-05-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0004_parada_tiempo_caminando'),
    ]

    operations = [
        migrations.AddField(
            model_name='parada',
            name='tipo',
            field=models.CharField(choices=[('OFICIAL', 'Oficial (Infraestructura Establecida)'), ('INFORMAL', 'Informal (Punto Frecuente por Costumbre)')], default='OFICIAL', help_text='Clasificación para el tratamiento de accesibilidad e infraestructura', max_length=15),
        ),
        migrations.AlterField(
            model_name='parada',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='parada',
            name='latitud',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='parada',
            name='longitud',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='parada',
            name='tiempo_caminando',
            field=models.IntegerField(help_text='Tiempo en minutos a la siguiente parada'),
        ),
    ]
