# Generated by Django 6.0.5 on 2026-05-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0005_parada_tipo_alter_parada_codigo_alter_parada_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parada',
            name='linea_emergencia',
            field=models.CharField(default='911 / (0286) 961-1111', help_text='Números de cuadrante de paz o asistencia local', max_length=50),
        ),
        migrations.AddField(
            model_name='parada',
            name='reportes_inseguridad',
            field=models.IntegerField(default=0, help_text='Contador de alertas de riesgo/luminaria'),
        ),
        migrations.AddField(
            model_name='parada',
            name='reportes_limpieza',
            field=models.IntegerField(default=0, help_text='Contador de alertas de mantenimiento'),
        ),
        migrations.AlterField(
            model_name='parada',
            name='tipo',
            field=models.CharField(choices=[('OFICIAL', 'Oficial (Infraestructura Establecida)'), ('INFORMAL', 'Informal (Punto Frecuente por Costumbre)')], default='OFICIAL', max_length=15),
        ),
    ]
