# Generated by Django 6.0.5 on 2026-05-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0006_parada_linea_emergencia_parada_reportes_inseguridad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrocinador',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_patrocinadores/'),
        ),
    ]
