# Generated by Django 6.0.5 on 2026-05-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0007_patrocinador_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='trazado',
            field=models.TextField(blank=True, help_text='Puntos GPS del recorrido', null=True),
        ),
    ]
