# Generated by Django 6.0.5 on 2026-05-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0008_ruta_trazado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('general', '📢 Aviso General (Banner)'), ('trafico', '🚗 Congestión / Retraso (Mapa)'), ('incidente', '⚠️ Accidente / Vía Cerrada (Mapa)')], default='general', max_length=20)),
                ('mensaje', models.CharField(help_text='Ej: Paro de transporte, vía cerrada en Alta Vista...', max_length=200)),
                ('activa', models.BooleanField(default=True, help_text='Desmarcar para quitar la alerta')),
                ('latitud', models.CharField(blank=True, max_length=50, null=True)),
                ('longitud', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
