# Generated by Django 6.0.5 on 2026-05-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0009_alertaoperativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ruta', 'Sugerencia de Ruta'), ('tranca', 'Reporte de Tranca/Congestión'), ('parada', 'Reporte de Parada/Tótem')], max_length=20)),
                ('sector', models.CharField(max_length=100)),
                ('referencia', models.CharField(blank=True, max_length=200)),
                ('detalles', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
