# Generated by Django 6.0.5 on 2026-05-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0010_sugerencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parada',
            name='linea_emergencia',
        ),
        migrations.RemoveField(
            model_name='parada',
            name='tiempo_caminando',
        ),
        migrations.AddField(
            model_name='parada',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Operativa'), ('INACTIVA', 'Clausurada / En Reparación')], default='ACTIVA', max_length=15),
        ),
        migrations.AddField(
            model_name='parada',
            name='referencia',
            field=models.CharField(blank=True, help_text='Ej: Frente al C.C. Orinokia', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='parada',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='parada',
            name='reportes_inseguridad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parada',
            name='reportes_limpieza',
            field=models.IntegerField(default=0),
        ),
    ]
