# Generated by Django 6.0.5 on 2026-05-24 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0011_remove_parada_linea_emergencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parada',
            name='tiempo_caminando',
            field=models.IntegerField(default=0, help_text='Minutos a pie hasta la parada'),
        ),
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('imagen_banner', models.ImageField(upload_to='campanas/')),
                ('activa', models.BooleanField(default=True)),
                ('patrocinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rutas.patrocinador')),
            ],
        ),
    ]
