# Generated by Django 6.0.5 on 2026-05-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0012_parada_tiempo_caminando_campana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='paradas',
            field=models.ManyToManyField(related_name='rutas', to='rutas.parada'),
        ),
    ]
